### ISSUE TITLE
Compare words coming on the fly

### ISSUE THREAD

**Issue by avinash-singh-io** [rahulsrma26/phonetic-word-embedding#1]
In the paper, it is mentioned that this algorithm can be used to compare the similarity of new words coming on the fly. So how I can achieve this implementation? @rahulsrma26 @KunalDhawan any help would be appreciated.

**Comment by rahulsrma26** [comment]
Hi @avinash539 
You can use [word_similarity](https://github.com/rahulsrma26/phonetic-word-embedding/blob/d81edef39c1534ca007cd6514a58ae914d72d0cf/src/similarity.py#L64) function directly as it doesn't depend on pretrained embedding it can deal with new words on the fly.
