### ISSUE TITLE
phonetics package

### ISSUE THREAD

**Issue by maherr13** [rahulsrma26/phonetic-word-embedding#2]
Hey, Great work!

Can I ask you what package did you use for writing the phonetics for each word ??

**Comment by maherr13** [comment]
Would you also share the checkpoint? 

Many Thanks @rahulsrma26  @KunalDhawan

**Comment by rahulsrma26** [comment]
@maherr13 Are you taking about language file [mapping_hindi.txt](https://github.com/rahulsrma26/phonetic-word-embedding/blob/345fed66eba0c5aaf01f38507c6a2954c1086c4c/res/mapping_hindi.txt)?

**Comment by rahulsrma26** [comment]
@maherr13 Are you taking about language file [mapping_hindi.txt](https://github.com/rahulsrma26/phonetic-word-embedding/blob/345fed66eba0c5aaf01f38507c6a2954c1086c4c/res/mapping_hindi.txt)?
