### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Hirak999** [rahulsrma26/phonetic-word-embedding#3]
I am getting the following error 

```
File "src/preprocess/vocab2dict.py", line 86
    description = f'; Autogenerated file using {os.path.basename(__file__)}\n' \

```
even after following all the steps that are mentioned in the readme while executing this command
`
python src/preprocess/vocab2dict.py res/hindi_phones.csv data/hindi_lm_large.vocab data/dict_hindi`

Any help on why this is taking place?

**Comment by rahulsrma26** [comment]
@Hirak999 May be LM format is changed or input file encoding is not compatible with "utf-8".  Are you using the environment same as "environment.yml"?

**Comment by rahulsrma26** [comment]
This issue was closed because it has been inactive for 6+ months.
