### ISSUE TITLE
unable to download pre trained hindi embedding. 

### ISSUE THREAD

**Issue by xorsuyash** [rahulsrma26/phonetic-word-embedding#4]
I am trying to build a ofline open-source version of google read_along app so model that i am using to transcript user voice is vosk ( 50Mb ) but the results for hindi transcript are not very satisfactory , so the approach that i came up with involves using acoustic similarity over vosk and facebook_denoiser to improove transcript accuracy ( WER, CER, Bleu) . but i am unable to download pre trained embedding for hindi words .
The drive that you shared in the repo shows following error 
   
![Screenshot from 2024-02-04 04-42-17](https://github.com/rahulsrma26/phonetic-word-embedding/assets/98162846/25d5005f-043b-4099-a92f-71a1732678a4)

**Comment by rahulsrma26** [comment]
@xorsuyash Thanks for reporting the problem. I think the problem could be google drive related. I have fixed this by pushing the pre-trained embeddings directly to the [repo subdirectory](https://github.com/rahulsrma26/phonetic-word-embedding/tree/dev/vector_embeddings). I have updated the [docs ](https://github.com/rahulsrma26/phonetic-word-embedding/tree/dev/embedding_hindi#training-embedding) to reflect that.
